import Link from "next/link";
import { ArrowRight, FileText, ShieldAlert } from "lucide-react";
import { productFamilies, applications, industries, type ProductFamily } from "@/data/catalog";

export function ValidationNote(){return <p className="rounded-md border border-amber-400/30 bg-amber-400/10 p-3 text-sm text-amber-100"><ShieldAlert className="mr-2 inline size-4"/>Final product selection requires review by qualified Urechem technical stakeholders.</p>}
export function FamilyCard({family}:{family:ProductFamily}){return <article className="rounded-lg border border-white/10 bg-white/[0.04] p-5 shadow-[var(--shadow-soft)]"><p className="font-mono text-xs uppercase tracking-[0.22em] text-cyan-300">{family.shortName}</p><h3 className="mt-3 text-xl font-semibold text-white">{family.name}</h3><p className="mt-3 text-sm leading-6 text-slate-300">{family.positioning}</p><div className="mt-4 flex flex-wrap gap-2">{family.products.slice(0,6).map(p=><Link key={p.slug} href={`/products/${family.slug}/${p.slug}`} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-200 hover:border-cyan-300">{p.name}</Link>)}</div><Link href={`/products/${family.slug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-cyan-300">View family <ArrowRight className="size-4"/></Link></article>}
export function DocumentStatus(){return <div className="rounded-lg border border-white/10 bg-navy-900 p-4"><h3 className="flex items-center gap-2 font-semibold"><FileText className="size-4 text-cyan-300"/>Document status</h3><p className="mt-2 text-sm text-slate-300">Technical documents are available on request when applicable. No placeholder downloads are published.</p></div>}
export function FamilyLinks({slugs}:{slugs:string[]}){return <div className="flex flex-wrap gap-2">{slugs.map(s=>{const f=productFamilies.find(x=>x.slug===s);return f&&<Link key={s} href={`/products/${s}`} className="rounded-full bg-cyan-300/10 px-3 py-1 text-sm text-cyan-100">{f.shortName}</Link>})}</div>}
export function AppLinks({slugs}:{slugs:string[]}){return <div className="flex flex-wrap gap-2">{slugs.map(s=>{const a=applications.find(x=>x.slug===s);return a&&<Link key={s} href={`/applications/${s}`} className="rounded-full bg-white/10 px-3 py-1 text-sm text-slate-100">{a.name}</Link>})}</div>}
export function IndustryLinks({slugs}:{slugs:string[]}){return <div className="flex flex-wrap gap-2">{slugs.map(s=>{const i=industries.find(x=>x.slug===s);return i&&<Link key={s} href={`/industries/${s}`} className="rounded-full bg-white/10 px-3 py-1 text-sm text-slate-100">{i.name}</Link>})}</div>}
