import Link from "next/link";
import { Container } from "@/components/ui/container";
import { SectionLabel } from "@/components/ui/section-label";

export const metadata = {
  title: "Privacy Policy",
  description: "How Urechem Chemicals collects, uses and protects information submitted through this website.",
};

const effectiveDate = "4 August 2026";

export default function Page() {
  return (
    <Container className="py-16 sm:py-20">
      <SectionLabel>Legal</SectionLabel>
      <div className="mt-5 max-w-4xl">
        <h1 className="text-4xl font-black tracking-[-0.04em] text-white sm:text-5xl">Privacy policy</h1>
        <p className="mt-4 text-sm font-semibold uppercase tracking-[0.14em] text-cyan-200">
          Effective and last updated: {effectiveDate}
        </p>
        <p className="mt-6 max-w-3xl text-base leading-8 text-slate-300">
          This policy explains how Urechem Chemicals handles information submitted through its website, contact forms,
          consultation pathways, document requests and AI-assisted product-discovery tools.
        </p>
      </div>

      <div className="mt-10 max-w-4xl space-y-10 text-base leading-8 text-slate-300">
        <section>
          <h2 className="text-2xl font-semibold text-white">1. Who operates this website</h2>
          <div className="mt-4 rounded-2xl border border-white/10 bg-white/[0.04] p-5 sm:p-6">
            <p className="font-semibold text-white">Urechem Chemicals</p>
            <p className="mt-2">002 SF, MU II, Industrial Road, Gautam Buddha Nagar, Uttar Pradesh 201310, India</p>
            <p className="mt-2">Telephone: +91 88821 32954</p>
            <p className="mt-2">
              Privacy requests may also be submitted through the{" "}
              <Link className="font-semibold text-cyan-100 underline underline-offset-4" href="/contact">
                contact page
              </Link>
              .
            </p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">2. Information we may collect</h2>
          <p className="mt-3">Depending on how you use the website, we may receive:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-cyan-300">
            <li>Your name, company name, job role, email address, telephone number and location.</li>
            <li>Product interests, application details, substrates, process conditions and performance requirements.</li>
            <li>Questions and information entered into consultation, contact, TDS/SDS or product-document request forms.</li>
            <li>Prompts and technical context entered into the AI Solution Finder or Ask Urechem AI tools.</li>
            <li>Files or documents that you intentionally provide for technical review.</li>
            <li>Basic technical information such as browser type, device type, IP address, timestamps and security logs where generated by the hosting platform.</li>
          </ul>
          <p className="mt-4">
            Please do not submit passwords, payment-card details, personal identity documents, confidential formulations,
            trade secrets or other information that is not necessary for the enquiry.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">3. How we use information</h2>
          <p className="mt-3">Information may be used to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-cyan-300">
            <li>Respond to commercial and technical enquiries.</li>
            <li>Identify potentially relevant product families and application pathways.</li>
            <li>Provide requested TDS, SDS, quotations, samples or supporting documents.</li>
            <li>Arrange consultations, testing discussions or follow-up communication.</li>
            <li>Improve website content, product discovery and enquiry workflows.</li>
            <li>Maintain security, prevent misuse and comply with applicable legal or regulatory obligations.</li>
            <li>Maintain reasonable business and enquiry records.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">4. AI-assisted tools</h2>
          <p className="mt-3">
            Information entered into an AI-assisted tool may be processed to prepare preliminary product-family guidance or
            a structured enquiry. Automated output may be incomplete, inaccurate or unsuitable for a particular application.
            It is not a final formulation, engineering, safety or purchasing decision and must be reviewed by an authorised
            Urechem representative before reliance or use.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">5. Consent and communication</h2>
          <p className="mt-3">
            By submitting a form or directly contacting Urechem, you ask us to use the supplied information to respond to
            your request and conduct related follow-up. You may ask us to stop non-essential follow-up communication at any
            time. Transactional, safety, legal or order-related messages may still be sent where necessary.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">6. Sharing and service providers</h2>
          <p className="mt-3">
            Information may be accessed by authorised Urechem personnel and by service providers needed to operate the
            website, hosting, security, email, document delivery or customer communication. These parties should receive
            only the information reasonably necessary for their role. Urechem does not sell personal information to
            advertisers or data brokers.
          </p>
          <p className="mt-3">
            Information may also be disclosed where required by law, a lawful authority, a court order, or to protect the
            rights, safety and security of Urechem, its customers or others.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">7. Cookies and browser storage</h2>
          <p className="mt-3">
            The website may use essential browser storage for functions such as remembering that an opening animation or
            consultation prompt has already been shown. This storage is not intended to contain enquiry text or contact
            details. If non-essential analytics, advertising or tracking technologies are introduced, this policy and any
            required consent controls will be updated.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">8. Retention</h2>
          <p className="mt-3">
            Information is retained only for as long as reasonably required to answer an enquiry, support a commercial or
            technical relationship, maintain records, resolve disputes, enforce agreements or meet legal and regulatory
            requirements. Information that is no longer required may be deleted, anonymised or securely archived.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">9. Security</h2>
          <p className="mt-3">
            Reasonable technical and organisational safeguards are used to protect information. However, no website,
            internet transmission or storage system can be guaranteed to be completely secure. Users should avoid sending
            highly sensitive information through ordinary website forms or email.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">10. Your choices and requests</h2>
          <p className="mt-3">
            Subject to applicable law, you may request access to, correction of or deletion of personal information held by
            Urechem, withdraw consent for optional processing, or raise a privacy grievance. We may need to verify your
            identity and may retain information where legally or operationally required.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">11. Children</h2>
          <p className="mt-3">
            This website is intended for businesses, technical professionals and adult users. It is not directed to
            children, and Urechem does not knowingly seek personal information from children through the website.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white">12. Updates to this policy</h2>
          <p className="mt-3">
            This policy may be revised when website functions, service providers or legal requirements change. The latest
            effective date will be displayed at the top of this page.
          </p>
        </section>

        <section className="border-t border-white/10 pt-8">
          <h2 className="text-2xl font-semibold text-white">Privacy contact</h2>
          <p className="mt-3">
            Urechem Chemicals, 002 SF, MU II, Industrial Road, Gautam Buddha Nagar, Uttar Pradesh 201310, India. Telephone:
            +91 88821 32954. You may also use the{" "}
            <Link className="font-semibold text-cyan-100 underline underline-offset-4" href="/contact">
              website contact form
            </Link>
            .
          </p>
        </section>
      </div>
    </Container>
  );
}
